{"version":"3.8.2","messages":["\nAn error occurred while loading ./spec/01_has_many_through_spec.rb.\n\u001b[31mFailure/Error: \u001b[0m\u001b[1;34;4mDir\u001b[0m[\u001b[1;34;4mFile\u001b[0m.join(\u001b[1;34;4mFile\u001b[0m.dirname(\u001b[1;36m__FILE__\u001b[0m), \u001b[31m\u001b[1;31m\"\u001b[0m\u001b[31m../lib\u001b[1;31m\"\u001b[0m\u001b[31m\u001b[0m, \u001b[31m\u001b[1;31m\"\u001b[0m\u001b[31m*.rb\u001b[1;31m\"\u001b[0m\u001b[31m\u001b[0m)].each {|f| require f}\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mSyntaxError:\u001b[0m\n\u001b[31m  /home/cerulean-programmer-9463/ruby-objects-has-many-through-readme-online-web-sp-000/lib/meal.rb:2: syntax error, unexpected tSYMBEG\u001b[0m\n\u001b[31m  ..._accessor :waiter, :customer. :total, :tip\u001b[0m\n\u001b[31m  ...                              ^\u001b[0m\n\u001b[36m# ./spec/spec_helper.rb:1:in `require'\u001b[0m\n\u001b[36m# ./spec/spec_helper.rb:1:in `block in <top (required)>'\u001b[0m\n\u001b[36m# ./spec/spec_helper.rb:1:in `each'\u001b[0m\n\u001b[36m# ./spec/spec_helper.rb:1:in `<top (required)>'\u001b[0m\n\u001b[36m# ./spec/01_has_many_through_spec.rb:1:in `require'\u001b[0m\n\u001b[36m# ./spec/01_has_many_through_spec.rb:1:in `<top (required)>'\u001b[0m\n","No examples found."],"examples":[],"summary":{"duration":0.000407594,"example_count":0,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":2},"summary_line":"0 examples, 0 failures, 2 errors occurred outside of examples"}